### ISSUE TITLE
PSR-6 cache application recommendation

### ISSUE THREAD

**Issue by sbillard** [Dolondro/google-authenticator#18]
Thank you for this library. I have it working in the ZenPhoto20 Media CMS application. But I am at a loss with the PSR-6 cache.  (Currently I have just disabled that replay attack prevention feature.) There seem to be many possible choices of cache handlers. But I really do not know what the needs of google-authenticator are and which choice might meet them with the lowest overhead.

I would really appreciate a suggestion (or two) from you.

**Comment by Dolondro** [comment]
Hi there!

To be honest, it probably doesn't matter so much which one you choose, the overhead of any of them will most likely be nothing.

I would personally either go with the using either the package `cache/filesystem` or `symfony/cache` adapter.

To try and make this more obvious, I've added `cache/filesystem` as a dev dependency and added an example of its usage inside `example.php`. Hopefully that should make the usage of it more obvious.

Hope your project goes well!
