### ISSUE TITLE
rawurlencode and getAccountName

### ISSUE THREAD

**Issue by FaimMedia** [Dolondro/google-authenticator#3]
https://github.com/Dolondro/google-authenticator/blob/master/src/Secret.php#L34

It would be better to use `rawurlencode` instead of `urlencode`, since it encoded spaces to `%20` instead of `+`.

Also, Google Authenticator shows the label as username, so it would be better to use `getAccountName` here, instead of `getLabel`. If you have a long issuer/company name, it showing pretty ugly with the colon appended.

**Comment by Dolondro** [comment]
The rawurlencode is fixed.

The label as a username thing seems to be at odds with my understanding, whereabouts are you seeing the colon appended that's offensive to the eye?

If you load a secret into an authenticator app, it separates them like so:

![image](https://cloud.githubusercontent.com/assets/1678803/18639427/81092ca2-7e59-11e6-893b-683acba2bfb2.png)
