### ISSUE TITLE
Timing attack

### ISSUE THREAD

**Issue by RobThree** [Dolondro/google-authenticator#31]
Your code is vulnerable to a [timing attack](https://thisdata.com/blog/timing-attacks-against-string-comparison/) because [you use a basic string comparison](https://github.com/Dolondro/google-authenticator/blob/b146e8caf6ce8edf61965ac9aba919e05dae7ae0/src/GoogleAuthenticator.php#L40). You should use [`hash_equals`](http://php.net/manual/en/function.hash-equals.php) or, if you need/want to support older versions than 5.6, a simple loop that iterates the entire string, regardless of the result [like this](https://github.com/RobThree/TwoFactorAuth/blob/f5f58a4c62d0336a0e6175856894a51f3565dad2/lib/TwoFactorAuth.php#L104) (disclaimer: author here).

Both your references have either addressed the issue or still have an active issue:

* [chregu/GoogleAuthenticator](https://github.com/chregu/GoogleAuthenticator.php/issues/22) - (currently) active issue 
* [PHPGangsta/GoogleAuthenticator](https://github.com/PHPGangsta/GoogleAuthenticator/blob/3baa997f399d4afd5d6a81d42244ec9cc3eeb080/PHPGangsta/GoogleAuthenticator.php#L231) - fixed

**Comment by Dolondro** [comment]
Seems legit, implemented and pushed out 👍

**Comment by RobThree** [comment]
Out of curiosity: where'd you find the [`substr_count` solution](https://github.com/Dolondro/google-authenticator/blob/bab70de88a58caf609cdb8066626d06ca6da997f/src/GoogleAuthenticator.php#L148) or did you come up with it yourself? It *could* be safe but I do have a little doubt; not sure yet.
